<h1 align="center">Copules</h1>

Maintenant nous allons nous intéresser à des données multivariées : ici la Seine et la Marne, qui est un de ses affluents.

L'idée est de pouvoir estimer : 

$$ \lambda_u = \underset{q \to 1}{\lim} \mathbb{P}(X_2 > F_2^{\leftarrow}(q) \vert X_1 > F_1^{\leftarrow}(q)) $$

# Récupération des données

In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import scipy.stats as stats
import seaborn as sns
import utils

In [2]:
seine = utils.load_data("DAHTI-8965-Seine.csv")
marne = utils.load_data("DAHTI-24129-Marne.csv")

In [4]:
seine.describe()

                         datetime         wse       wse_u   elevation
count                         605  605.000000  605.000000  605.000000
mean   2017-05-31 21:05:39.614876   69.517261    0.046288    1.296261
min           2008-07-23 07:55:10   68.221000    0.000000    0.000000
25%           2012-11-25 19:59:15   69.114000    0.013000    0.893000
50%           2017-03-31 08:04:56   69.323000    0.028000    1.102000
75%           2021-11-10 23:54:34   69.709000    0.066000    1.488000
max           2026-03-16 11:59:06   71.909000    0.470000    3.688000
std                           NaN    0.637397    0.052181    0.637397

In [5]:
marne.describe()

                         datetime         wse       wse_u   elevation
count                         117  117.000000  117.000000  117.000000
mean   2021-02-12 04:48:52.367521  104.371598    0.111504    1.212598
min           2016-05-06 10:20:55  103.159000    0.001000    0.000000
25%           2018-09-17 10:21:04  103.879000    0.038000    0.720000
50%           2021-01-28 10:21:15  104.266000    0.080000    1.107000
75%           2023-06-11 10:21:15  104.786000    0.139000    1.627000
max           2026-02-07 10:21:24  106.026000    0.489000    2.867000
std                           NaN    0.683157    0.106851    0.683157

On voit que l'on a beaucoup moins de données sur la Marne, on va essayer de se restreindre à la partie commune et de récupérer une seule valeur par mois.